### ISSUE TITLE
Nest uiowa_alerts.settings configuration as collection

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#1720]
Not sure why I underscored it but it should be a collection:
```
hawk_alert:
  display: true
  source: ...
custom_alert:
  display: false
...
```
Requires a DB update to migrate existing config.
