### ISSUE TITLE
Layout Builder highlight is showing while inline block is being edited

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1851]
<img width="1347" alt="Screen Shot 2020-06-25 at 5 13 50 PM" src="https://user-images.githubusercontent.com/709009/85801257-1e0cd400-b708-11ea-9fe2-c1a6d81bc9e9.png">

The image above is from production.

It seems to be caused by the following style:
```css
.layout-builder-block.is-layout-builder-highlighted {
    border: 4px solid #000;
}
```

The outline isn't a problem per se, but it is showing up on the title in addition to showing around the block.
