### ISSUE TITLE
Syncing files from new local DDEV environment to stage/production doesn't work due to a different/broken path in drush command

### ISSUE THREAD

**Issue by quamsta** [uiowa/uiowa#4573]
# Problem

For example:

When running `drush @studenthealth.local rsync @self:%files @studenthealth.prod:%files`

You get the error:

```
> rsync: [sender] change_dir "/var/www/html/sites/studenthealth.uiowa.edu/files" failed: No such file or directory (2)
> rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
```

Due to the path changing slightly from:

`/var/www/sites/studenthealth.uiowa.edu/files`

to:

`/var/www/docroot/sites/studenthealth.uiowa.edu/files`

# Steps to reproduce
Attempt to push up files from local to stage or prod.

# Proposed solution

## Idea 1:
Update this entry in drush/sites/[sitename].site.yml:

```
local:
  root: /var/www/html
  uri: studenthealth.uiowa.ddev.site
  paths:
    files: sites/studenthealth.uiowa.edu/files
```

to

```
local:
  root: /var/www/html
  uri: studenthealth.uiowa.ddev.site
  paths:
    files: docroot/sites/studenthealth.uiowa.edu/files
```

Also, ensure that the script used to initiate/create these drush commands gets updated, too

## Idea 2:

Alter DDEV environment to mirror/match prod/stage a bit more closely, including the file structure in the container. This is a bit over my head.
