### ISSUE TITLE
Moving forward with parallel deployments

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8004]
As part of https://github.com/uiowa/uiowa/issues/7800, we tried out running parallel deployments and it seems like we are seeing quicker deployment times but still not sure it will get us below an hour for all applications. What are our next steps to tidy up this work or to ensure deployments will be less than an hour?
```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/8015
- [ ] https://github.com/uiowa/uiowa/issues/8016
```

**Comment by pyrello** [comment]
A few options:
1. At the point where we invoke the parallel processing command, we could pipe that output to a log file just to have it since the AC task log doesn't stick around long enough to be useful a lot of the time. This could be done to provide a more robust feedback system regardless of whether we use those logs for further processing.
2. We could experiment with swapping out the method we are using for error-checking in parallel processing to use log file output instead of assigning the output to a variable. This might be both more performant and less susceptible to failure based on trying to assign to much data to a variable.
3. Our current process doesn't pre-filter the list of sites to just include sites from the application it is being run on. Instead it checks if a config file exists for each site and then only continues execution for sites where it finds one. We have 1259 v2/v3 sites as of this writing, but the largest application has only 223 sites. That means we are doing at least >1000 checks for a non-existent file. Even with parallel processing, that means that each of those sites that doesn't exist on that application gets to temporarily occupy one of the 3 processing slots. We could create a mechanism to filter the list before the site updates are initiated and it would likely save us some time vs checking sites that aren't there as part of the update process. This would also help us clean up the log output and make it easier to read the logs because there wouldn't be a lot of noise related to 1000+ sites being "skipped".

**Comment by briand44** [comment]
Grooming conversation... 

1. The log file doesn't do anything to speed up deployments but it would allow us to be less dependent on Acquia logs and would give us the ability to have this information around longer and possibly do more with it. Team feels there is added value in this.
2. It's possible this could increase performance. We would need to set up the log file in # 1 for this to work. Search for `error`. Variable can get extremely large and could potentially be too big and cause failures. If the log file slows things down at least it delays that until later. Team feels like #1 and #2 could be grouped together in a slice. - 1&2 - medium
3. Currently the existing implementation can run on any environment/application and we want to keep that ability. Could increase performance. Sean thinks we have access to the information we need at this point through some sort of Environment Variables. Sean suggesting to store application in blt.yml. Would need to use BLT platform update system. The `umd` command looks up the application currently via drush file so we could potentially do something like this as well. Still may be more performant if storing in blt.yml. - Medium

**Comment by pyrello** [comment]
> Sean suggesting to store application in blt.yml

To be clear, this would be an entry in the `blt.yml` file like: 
```yml
application: uiowa07
```
Ideally, it would be an exact match to whatever we get as the application when checking an environment variable.

As @joewhitsitt pointed out, this would require updating our provisioning script. However, I think we could get a very slight performance boost from doing this, which we would get to enjoy for every deployment we run after its implemented. The extra work to update our provisioning script would likely be a onetime cost.

**Comment by joewhitsitt** [comment]
> this would require updating our provisioning script

and transfer script, \Uiowa\Blt\Plugin\Commands\MultisiteCommands::transfer

could simplify the delete command too by not relying on `getApplicationFromDrushRemote`

**Comment by GaryRidgway** [comment]
Would the `uiowa/drush/sites/*.yml` files work for this? They don't have the app exactly, but their hosts start with the app name split on a period, which is pretty close?

<details><summary>Example for researchanimal.site.yml</summary>

```

local:
  root: /var/www/html/docroot
  uri: researchanimal.uiowa.ddev.site
  paths:
    files: sites/animal.research.uiowa.edu/files
dev:
  uri: researchanimal.dev.drupal.uiowa.edu
  host: uiowa07dev.ssh.prod.acquia-sites.com
  options: {  }
  paths:
    dump-dir: /mnt/tmp
    files: sites/animal.research.uiowa.edu/files
  root: /var/www/html/uiowa07.dev/docroot
  user: uiowa07.dev
prod:
  uri: animal.research.uiowa.edu
  host: uiowa07prod.ssh.prod.acquia-sites.com
  options: {  }
  paths:
    dump-dir: /mnt/tmp
    files: sites/animal.research.uiowa.edu/files
  root: /var/www/html/uiowa07.prod/docroot
  user: uiowa07.prod
test:
  uri: researchanimal.stage.drupal.uiowa.edu
  host: uiowa07stage.ssh.prod.acquia-sites.com
  options: {  }
  paths:
    dump-dir: /mnt/tmp
    files: sites/animal.research.uiowa.edu/files
  root: /var/www/html/uiowa07.stage/docroot
  user: uiowa07.stage

```

</details>
