### ISSUE TITLE
Adjust accordion js to work with uids_base

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#8454]
# Problem
During the recent accordion testing, there was a console error related to the accordion JS.

```
Uncaught SyntaxError: Unexpected token 'export' (at accordion.js?sqiel8:121:1)
```

https://github.com/uiowa/uiowa/pull/8405#issuecomment-2610189111

# Proposed solution
- [x] Implement a similar solution as we did for [click-a11y-init.js](https://github.com/uiowa/uiowa/pull/6450)
- [x] Confirm that this resolves the issue with the hash fragment not getting populated or triggering the browser to scroll to the linked element.
- [ ] Follow-up with Ben L when this is fixed.

**Comment by quamsta** [comment]
Not sure if related, it but it looks like anchors aren't being added to URLs upon clicking accordion titles/expanding them, conversely, anchors in the URL on page load aren't opening accordions.

**Comment by joewhitsitt** [comment]
Slack thread: https://iowaweb.slack.com/archives/C0164FNN1PV/p1738616805967189

Copy/pasta my Slack comment:

>https://github.com/uiowa/uids/pull/955/files seems to show that the accordion by hash is still in there, but the window history stuff was removed.

**Comment by joewhitsitt** [comment]
Created a separate UIDS issue to fix the accordion item id not being added to the address bar of the browser. https://github.com/uiowa/uids/issues/973

**Comment by briand44** [comment]
Grooming conversation... Look at git blame on https://github.com/uiowa/uiowa/pull/6450. We think that the accordion.js is not getting loaded.

**Comment by pyrello** [comment]
> Grooming conversation... Look at git blame on [#6450](https://github.com/uiowa/uiowa/pull/6450). We think that the accordion.js is not getting loaded.

Adding some context to this. We started to groom https://github.com/uiowa/uids/issues/973 and then realized that the ID hash was getting populated correctly but you had to be on the standalone page in Storybook for the accordion component to see it happen (otherwise it happens in an iframe and you don't see that in the main window URL).

I noted that because we are using the `<details>` element, we see some behavior working that was previously JS and maybe it looks like the JS is partially functional. But because that behavior is actually handled by the HTML element itself, we no longer have JS to handle that toggling. Therefore, I think that the issue is that the JS file just isn't getting loaded correctly and that is breaking all the accordion JS functionality, including the hash ID stuff.

**Comment by pyrello** [comment]
Noting that a report of the hash id functionality missing from accordions came in via support from Ben L.

**Comment by pyrello** [comment]
I just checked and making the following update resolves the issue with the console error in the IS:

Current:
```yaml
accordion:
  css:
    component:
      assets/css/components/accordion.css: { preprocess: false }
      assets/css/paragraphs/uiowa_paragraphs_accordion.css: { preprocess: false }
  js:
    uids/assets/js/accordion.js: { preprocess: false }
```

Updated:
```yaml
accordion:
  css:
    component:
      assets/css/components/accordion.css: { preprocess: false }
      assets/css/paragraphs/uiowa_paragraphs_accordion.css: { preprocess: false }
  js:
    uids/assets/js/accordion.js: { preprocess: false, attributes: { type: module } }
```

After making this change, the hash functionality still doesn't seem to be working as expected.
