### ISSUE TITLE
Page Title Hero on hr.stage.drupal.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8551]
>I’m trying to add a Page Title Hero in stage, and it isn’t letting me. I select insert and it does nothing.
https://hr.stage.drupal.uiowa.edu/
 
Should the Page Title Hero be an option on a V2 site with P2LB enabled? Should they be using Banner instead? Anything we need to address with this or is it working as designed?

**Comment by briand44** [comment]
Grooming conversation... Usually this is a setting core_node_type_entity_view_display? config that needs to be excluded. If this isn't just happening on HR, we may need to audit some sites that have previously converted using P2LB. We could use a db query to search for instances of that block type. Probably have an example of this somewhere:

``` SELECT count(*) FROM block_content WHERE type = 'uiowa_event'```

or search contents of the layout field?

``` ./vendor/bin/blt ume "sqlq \"SELECT entity_id from node_revision__layout_builder__layout WHERE layout_builder__layout_section LIKE '%uiowa_core_search_block%';\"" ```

**Comment by pyrello** [comment]
Pretty sure this is the problem (from `config/sites/hr.uiowa.edu/core.entity_view_display.node.page.default.yml`):
```
  layout_builder_restrictions:
    allowed_block_categories: {  }
    entity_view_mode_restriction:
      allowed_layouts: {  }
      denylisted_blocks: {  }
      allowlisted_blocks: {  }
    entity_view_mode_restriction_by_region:
      allowed_layouts: {  }
      allowlisted_blocks: null
      denylisted_blocks: null
```
